ALTER TABLE "Collection" ADD COLUMN "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Collection" ADD COLUMN "endDate" TIMESTAMP(3);
ALTER TABLE "Collection" ALTER COLUMN "startDate" DROP DEFAULT;
